@startuml diagrama_estados
!theme plain

state Inicio ##[bold]green
state Prepara: zera_sensor_agua=1 \nzera_sensor_xicara=1 \nzera_bomba=1 \nzera_valvula=1 \nzera_serial=1 \nzera_timeout_ebulidor=1

state EsperaModo

state PreparaSensorAgua: zera_sensor_agua=1 
state AtivaSensorAgua: medir_agua=1
state EsperaSensorAgua ##[bold]aqua: conta_timeout_agua=1

state PreparaSensorXicara: zera_sensor_xicara=1 
state AtivaSensorXicara: verifica_xicara=1
state EsperaSensorXicara ##[bold]aqua: conta_timeout_xicara=1

state ErroSemAgua ##[bold]red:     erro_sem_agua=1
state ErroSemXicara ##[bold]red:   erro_sem_xicara=1

state AtivaBomba:      ativa_bomba=1 \nconta_bomba=1

state AtivaEbulidor:   ativa_ebulidor=1 \nconta_timeout_ebulidor=1
state ErroEbulidor ##[bold]red:    erro_ebulidor=1

state AtivaValvula:    ativa_valvula=1 \nconta_valvula=1
state Fim ##[bold]red:             fim=1

[*]               --> Inicio
Inicio            --> Inicio: preparar = 0
Inicio            --> Prepara: preparar = 1
Prepara           --> EsperaModo

EsperaModo --> EsperaModo: pronto_serial=0
EsperaModo --> PreparaSensorAgua: pronto_serial=1

PreparaSensorAgua --> AtivaSensorAgua : ‎‎‎
AtivaSensorAgua --> EsperaSensorAgua
EsperaSensorAgua  --> PreparaSensorAgua : timeout_agua=1 & pronto_sensor_agua=0
EsperaSensorAgua  --> ErroSemAgua : pronto_sensor_agua=1 && suficiente=0
EsperaSensorAgua  --> PreparaSensorXicara : pronto_sensor_agua=1 && suficiente=1
EsperaSensorAgua --> EsperaSensorAgua : pronto_sensor_agua=0 && timeout_agua=0

PreparaSensorXicara  --> AtivaSensorXicara : ‎‎‎
AtivaSensorXicara --> EsperaSensorXicara
EsperaSensorXicara  --> PreparaSensorXicara : timeout_xicara=1 & pronto_sensor_xicara=0
EsperaSensorXicara  --> ErroSemXicara : pronto_sensor_xicara=1 && tem_xicara=0
EsperaSensorXicara  --> AtivaBomba : pronto_sensor_xicara=1 && tem_xicara=1
EsperaSensorXicara --> EsperaSensorXicara : pronto_sensor_xicara=0 && timeout_xicara=0

AtivaBomba --> AtivaBomba : fim_bomba=0
AtivaBomba --> AtivaEbulidor: fim_bomba=1

AtivaEbulidor --> AtivaEbulidor: fim_ebulidor=0 && timeout_ebulidor=0
AtivaEbulidor --> ErroEbulidor: timeout_ebulidor=1
AtivaEbulidor --> AtivaValvula: fim_ebulidor=1
ErroEbulidor --> Inicio

AtivaValvula --> AtivaValvula: fim_valvula=0

AtivaValvula --> Fim: fim_valvula=1
Fim --> Inicio


ErroSemAgua --> Inicio
ErroSemXicara --> Inicio


@enduml